apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kyctg-api.fullname" . }}-configmap
data:
  SECRET_PATH: "/app/secrets/apiSecrets"
  DOCKER_BUILD_SOURCE: "."
  Auth0__Authority: "https://{{ .Values.global.auth0.domain }}"
  Auth0__Audience: "{{ .Values.global.auth0.audience }}"
  ASPNETCORE_ENVIRONMENT: "{{ .Values.global.env.aspNetEnvironment }}"
  SITKA_EMAIL_REDIRECT: "{{ eq .Values.global.env.aspNetEnvironment "Production" | ternary "" "notifications-qa@sitkatech.com" }}"
  WEB_URL: "https://{{ .Values.global.domains.web }}"
  PlatformLongName: "Know Your Cost to Grow"